#!/usr/bin/env python3

import sys

from rqt_gui.main import Main
from rqt_ez_publisher import ez_publisher_plugin

main = Main()
sys.exit(main.main(sys.argv, standalone='rqt_ez_publisher',
                   plugin_argument_provider=ez_publisher_plugin.add_arguments))
